BBBBBBB BBBBBBBBBBBB

BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBB
    XXX XX
BBBBBBBB

BBBBB BBBBBBB
    XXXXX XXXXXXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        FFFFFF
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX
BBBBBBBB