BBBBBBB BBBBBBBBBBBB


BBBBB BBBBBBBBBB
    XXX XXX
BBBBBBBB

BBBBB BBBBBBB
    XXXXXXX XXXXXXXX
    XXXXX XXXXXXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXX
    XXXXXXX
BBBBBBBB